version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - postgres
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_monitor_db
      POSTGRES_HOST: postgres
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_monitor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
